spring:
  main:
    banner-mode: off
  data:
    mongodb:
      host: localhost
      port: 27017
      database: boot_mongodb
      username: mongouser
      password: password

app:
  http:
    server:
      ssl:
        port: 8443
      port: 8081
  tcp:
    server:
      port: 10003
  jwt:
    issuer: stomp-rabbit-spring-server
    secretKey: securesecuresecuresecuresecuresecuresecuresecuresecuresecuresecure
    tokenPrefix: Bearer
    tokenExpirationAfterDays: 10
  stomp:
    endpoint: /stomp-ws
    allowedOrigins: '*'
    userDestinationPrefix: /client
    appDestinationPrefix: /v1
    destinationToken: '-'
    destinationType: queue
    tls:
      version: TLSv1.2
      client:
        keyPassword: bunnies
        key-store-type: PKCS12
        keyLocation: /home/dell/shreyas/Programming/BitBucketRepositories/stomp-rabbit/src/main/resources/ssl/Server/tls-gen/client_key.p12
      server:
        trustPassword: prvt1Key
        trust-store-type: JKS
        cert-file: /home/dell/shreyas/Programming/BitBucketRepositories/stomp-rabbit/src/main/resources/ssl/Server/tls-gen/rabbit_truststore.p12
        trust-manager-type: SunX509
    client:
      login: shred22
      password: password
    broker:
      host: localhost
      port: 61614
      login: shred22
      password: password
      relay: /exchange
    outbound:
      thread-pool-size: 5

security:
  require-ssl: true
server:
  port: 8443
  ssl:
    key-alias: spboot-stomp-server-ssl
    key-store: classpath:ssl/Server/spboot-stomp-http.p12
    key-store-password: prvt1Key
    key-store-type: PKCS12
logging:
  level:
    org.springframework.messaging.simp: INFO
    org.springframework.security: INFO
    org.springframework.amqp: INFO
    org.springframework.boot: INFO